---
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.1.0
  amd64: ghcr.io/hassio-addons/base:18.1.0
  armv7: ghcr.io/hassio-addons/base:18.1.0
codenotary:
  base_image: ghcr.io/hassio-addons/base
  signer: haim-b
